FDG-8440 Update Homepage with new Savings Bonds Tile
fedspendingtransparency/fiscal-data pull request #1145
Opened 2024-03-21 13:45 UTC by nicweidner

**Description**

Adding Treasury Savings Bonds to homepage 

[**Jira Story**](https://federal-spending-transparency.atlassian.net/browse/FDG-8440)

**Test Coverage**
All files (% lines): 90.65%
![image](https://github.com/fedspendingtransparency/fiscal-data/assets/159341849/7ba861f1-6da0-4fd6-8a48-4d05e5c8c0e0)
 topics-section.jsx: 100%
![image](https://github.com/fedspendingtransparency/fiscal-data/assets/159341849/494cfd19-0678-4407-b0f9-be3d9b7e0994)

2024-03-22 13:28 UTC, jdach requested changes
Looking good! Other than adding an evergreen fiscal year to the api call, can you add a unit test covering the SavingsBondsBodyGenerator?

2024-03-22 13:28 UTC, jdach commented on src/components/topics-section/homepage-tile/homepage-tile-helper.js
> +  const sbUrl = `v1/accounting/od/securities_sales?filter=security_type_desc:eq:Savings%20Bond,record_fiscal_year:eq:2023`;
The record fiscal year used in this api call should be evergreen

2024-03-22 21:13 UTC, nicweidner commented on src/components/topics-section/homepage-tile/homepage-tile-helper.js
> +  const sbUrl = `v1/accounting/od/securities_sales?filter=security_type_desc:eq:Savings%20Bond,record_fiscal_year:eq:2023`;
Made that dynamic! Let me know if you see anything wrong with the approach.

2024-03-25 15:29 UTC, jdach commented on src/components/topics-section/homepage-tile/homepage-tile-helper.js
> +  function getPreviousFiscalYear() {
When you grab the previous fy here, it needs to be based on the latest available data rather than the current date

(Also very minor comment, we typically use arrow function notation)

2024-03-25 15:31 UTC, jdach commented on src/components/topics-section/homepage-tile/homepage-tile-helper.js
> +          savingsBondsTotal = savingsBondsTotal + parseInt(index.gross_sales_amt);
I just confirmed with data that this should be net_sales_amt rather than gross_sales_amt

2024-03-25 16:44 UTC, jdach approved these changes
Changes look great!

2024-03-25 16:53 UTC, merged