FDG-9491 Events udpate
fedspendingtransparency/fiscal-data pull request #1366
Opened 2024-08-28 18:14 UTC by chasls2

https://federal-spending-transparency.atlassian.net/browse/FDG-9491

no change in test coverage

2024-09-05 13:07 UTC, jdach commented on static/data/ga-event-tracking/spendingExplainerEventTracking.csv
> +30,Click on the link to the Daily Treasury Statement,Fiscal Data - Explainers,Spending Citation Click,Monthly Treasury Statemen,
Statement is missing a 't'

2024-09-05 13:07 UTC, jdach commented on src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
> +        {' '}
Space should be moved outside the link

2024-09-05 13:10 UTC, jdach commented on static/data/ga-event-tracking/spendingExplainerEventTracking.csv
> +13,"Click on the toggle to ""Dollars""",Fiscal Data - Explainers,Chart Toggle,Spending
Trailing comma is missing

2024-09-06 15:57 UTC, jdach requested changes
National Debt Page
- The 'What is the National Debt?' Debt to the Penny link should have Debt to the Penny set as the eventLabel
Spending Explainer Page
- Agency Profile event should have 'Agency Profile' as the event label instead of 'Agency Profiles'
- MTS Link on the U.S. Government spending chart has "Spending - Spending Categories" as the eventLabel but it should be 'Monthly Treasury Statement (MTS)'

2024-09-06 16:56 UTC, nicweidner commented
Updated Agency Profile! 
![image](https://github.com/user-attachments/assets/bafb36a7-51ad-48c2-9f91-23fa5e232c5d)

2024-09-09 17:35 UTC, nicweidner commented
Updated MTS
![image](https://github.com/user-attachments/assets/0064cda4-a243-4e6c-820d-b68390d8d156)

2024-09-09 19:14 UTC, jdach approved these changes
Changes look good!

2024-09-09 19:14 UTC, merged