Fdg 6002 Hook in the Data for Variable Data Elements on the Spending Explainer page
fedspendingtransparency/fiscal-data pull request #180
Opened 2022-09-08 15:36 UTC by j-hertzler

https://federal-spending-transparency.atlassian.net/browse/FDG-6002
Code coverage: 89.56%

2022-09-08 17:44 UTC, fzafrb commented
@j-hertzler let me know if you'd like a second set of eyes in resolving this merge conflict, they are from the PR of mine that you just merged in. thx

2022-09-08 17:49 UTC, j-hertzler commented
> @j-hertzler let me know if you'd like a second set of eyes in resolving this merge conflict, they are from the PR of mine that you just merged in. thx
I got them resolved, but thank you!

2022-09-09 17:00 UTC, wyattch requested changes
Currently one failing test locally

2022-09-09 20:31 UTC, wyattch approved these changes

2022-09-09 20:31 UTC, merged