Fdg 5920 - G-Develop Initial AFG Overview Page
fedspendingtransparency/fiscal-data pull request #182
Opened 2022-09-08 16:55 UTC by jsmend0za-frb

The new AFG Overview page is created using the Zeplin design mock, adding key page elements such as SEO title/description/H1, Table of Contents, sections headings, dummy text, images, and DS&M. Note for the Year-in-Review section - the header copy was changed since the mock was created. The mock can still be followed for font size/coloring. For the use of emphasis coloring, for Revenue that color can be applied to the word ‘collect’;  for Spending the word ‘spent’; for Deficit the word ‘deficit’; and for Debt the word ‘debt’.

A placeholder is added for the social share component since that work will be completed later with [FDG-5921](https://federal-spending-transparency.atlassian.net/browse/FDG-5921).

The URL for the new page is: https://fiscaldata.treasury.gov/americas-finance-guide/

Ensure on mobile that the copy on the Statue of Liberty image is clear (timebox this).

The page is responsive for desktop and mobile devices.

Code Coverage: 89.41

https://federal-spending-transparency.atlassian.net/jira/software/c/projects/FDG/boards/44?modal=detail&selectedIssue=FDG-5920&assignee=6304f22ca29ccf49383889f2&assignee=62fbed9be2b1b5ae159aa4c9

2022-09-13 14:41 UTC, j-hertzler commented on src/pages/americas-finance-guide/index.jsx
> +        pageTitle="America’s Finance Guide | U.S. Treasury Fiscal Data"
U.S. Treasury Fiscal Data can be removed here

2022-09-13 14:48 UTC, j-hertzler commented on src/pages/americas-finance-guide/afg-components/compare-section/compare-section.module.scss
> +    // .compareGridContainer{
Remove commented out code

2022-09-13 15:03 UTC, j-hertzler commented on src/pages/americas-finance-guide/afg-overview.module.scss
> +    color: #b3532d
Update to use color variables where possible

2022-09-13 21:38 UTC, j-hertzler requested changes
The changes look good and address most comments. 
New / remaining issues : 
- Learn more about federal spending link is the wrong color
- On mobile, images should be above their section header, rather than below (example of this is in the image previously added to this pr)

2022-09-14 12:33 UTC, jsmend0za-frb commented
I have address these comments and should be fixed now. Thanks.

2022-09-14 15:28 UTC, j-hertzler approved these changes
Changes look good. Tests and build pass locally

2022-09-15 16:32 UTC, merged