FDG-6464 AFG Deficit Explainer - Apply Copy Updates
fedspendingtransparency/fiscal-data pull request #472
Opened 2023-01-23 23:09 UTC by wyattch

Coverage: 90.07%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6464

2023-01-24 16:22 UTC, wyattch commented
PR is currently blocked

2023-01-27 19:42 UTC, j-hertzler requested changes
A couple of weird glossary issues to correct but otherwise looks good

2023-01-27 19:42 UTC, j-hertzler commented on static/data/glossary/glossary.csv
> +14,Federal Debt,Spending Explainer,The federal debt is the total amount of outstanding borrowing by the U.S. federal government accumulated over the nation�s history. ,,
Needs to be corrected back to an apostrophe

2023-01-27 19:42 UTC, j-hertzler commented on static/data/glossary/glossary.csv
> +33,Trust fund,Revenue Explainer,A type of account for revenue or offsetting revenue dedicated to specific purposes and the spending of that revenue. Some revolving funds are designated as trust funds
Remove strange character here

2023-01-27 19:42 UTC, j-hertzler commented on static/data/glossary/glossary.csv
> +15,Fiscal Year,"Debt, Deficit, Revenue & Spending explainer","The fiscal year is an accounting period spanning 12 months. For the federal government, it runs from October 1 to September 30. For examp
Correct characters here

2023-01-27 19:42 UTC, j-hertzler commented on static/data/glossary/glossary.csv
> +7,Calendar Year,Debt explainer,This is the one-year period between January 1 and December 31. This is different from the U.S. Government�s fiscal year.,,
Needs to be corrected back to an apostrophe

2023-01-27 21:01 UTC, j-hertzler approved these changes
Changes look good

2023-01-27 21:01 UTC, merged