FDG-4933 Line chart with multiple scales
fedspendingtransparency/fiscal-data pull request #53
Opened 2022-06-10 15:12 UTC by tompurkaple

https://federal-spending-transparency.atlassian.net/browse/FDG-4933

Includes implementation (FDG-4698).
https://federal-spending-transparency.atlassian.net/browse/FDG-4698

Some linting fixes, page layout/wrapping adjustments

Test coverage: 89.02

2022-06-10 20:22 UTC, wyattch commented on src/layouts/explainer/sections/national-debt/national-debt.spec.js
> +      elem = getByTestId('interest-and-debt-chart-header');
Is it possible to tie these values to variables that could be changed (via mock data) instead of raw text values?

2022-06-10 20:28 UTC, wyattch requested changes
I'm still in the process of going through the code, but in the meantime I noticed the following things on local that differed from the design mocks: 

- The top line of the dual line chart should be blacker, not blue (an example of the proper color is found in the debt trends chart config in national-debt.jsx in master)
- The black hatch line pattern for the bottom line chart can be removed so that it is solid purple. 
- The distance between header items (fiscal year, average interest rate, total debt) should be 2rem, right now it looks a little wider. 

I would also advise pulling down the latest code from master so that merge conflicts can be sorted out. 

Otherwise, the typescript is looking really clean and it's amazing the amount of effort that went into this.

2022-06-10 21:40 UTC, tompurkaple commented
@wyattch , I see the point about the header spacing, but I don't  notice a blue line or a black hatching.  I this how it looks on your screen?

![image](https://user-images.githubusercontent.com/54994583/173154687-a187016f-e918-460b-943d-93706c096ce7.png)

2022-06-14 14:38 UTC, wyattch commented on src/utils/mock-utils.ts
> +/*export const determineResponseForDebtBreakdownSection = (
Can this commented method be removed?

2022-06-14 14:39 UTC, wyattch requested changes
The spacing between the header items and title needs to be increased to 2rem (preferably in a class specific to this chart)

2022-06-16 15:04 UTC, tompurkaple commented on src/utils/mock-utils.ts
> +/*export const determineResponseForDebtBreakdownSection = (
Good catch.  Thanks!

2022-06-16 15:08 UTC, tompurkaple commented on src/layouts/explainer/sections/national-debt/national-debt.spec.js
> +      elem = getByTestId('interest-and-debt-chart-header');
Now importing a mock variable closely nestled with the corresponding data with these values.

2022-06-16 18:11 UTC, wyattch approved these changes
Changes look good. Tests and build pass and chart looks aligned with mocks. Great job.

2022-06-16 18:11 UTC, merged