Fdg 7401 - Create GA4 events for DDP
fedspendingtransparency/fiscal-data pull request #658
Opened 2023-06-09 20:12 UTC by hmargy

https://federal-spending-transparency.atlassian.net/browse/FDG-7401

no changes in test coverage

2023-06-12 17:08 UTC, wyattch requested changes
Currently, I am unable to get the cancel download tag to fire when clicking the button

2023-06-12 17:08 UTC, wyattch commented on src/components/dataset-card/dataset-card.tsx
> +        // GA4 Data Layer - Related Dataset Click
Right now, this triggers whenever a dataset card is clicked and not when it is just a related dataset

2023-06-12 18:26 UTC, hmargy commented on src/components/dataset-card/dataset-card.tsx
> +        // GA4 Data Layer - Related Dataset Click
good catch! I'll look into this

2023-06-14 16:36 UTC, hmargy commented on src/components/dataset-card/dataset-card.tsx
> +        // GA4 Data Layer - Related Dataset Click
changes have been added

2023-06-14 18:11 UTC, wyattch requested changes
Changes look great! One final thing I noticed is that when clicking on some datasets at random, I noticed that the date picker tag would fire when clicking on the dataset card from the search page. Could this be looked into?

2023-06-14 21:31 UTC, hmargy commented
This is consistent with the current universal analytic logic

2023-06-14 21:36 UTC, wyattch approved these changes
Changes look good. Approved.

2023-06-14 21:36 UTC, merged