Fdg 7675Research Spending & Revenue chart animation implementation
fedspendingtransparency/fiscal-data pull request #790
Opened 2023-09-19 17:06 UTC by chasls2

[FDG-7675](https://federal-spending-transparency.atlassian.net/browse/FDG-7675)

Animation across the graph

2023-09-20 18:51 UTC, wyattch requested changes
Had a few comments, everything else looks good

2023-09-20 22:35 UTC, chasls2 commented on src/layouts/experimental/charts/lineGraph.jsx
> +      {/* {mouseHover === null && (
I forgot all about all the lineGraph stuff I didn't revert

2023-09-20 22:41 UTC, chasls2 commented on src/layouts/experimental/charts/lineGraph.jsx
> +          console.log('Enter: ', setMouseHover(slice.slicePoints[0].x));
user currently aren't using this file. My bad I kind of just forgot about it

2023-09-22 17:06 UTC, wyattch approved these changes
Approved

2023-09-22 17:06 UTC, merged