FDG-7769 General Site Updates - Make Dropdown Search height flexible for < 5 menu items
fedspendingtransparency/fiscal-data pull request #963
Opened 2023-12-21 20:29 UTC by wyattch

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7769
Coverage: 89.85%

2023-12-22 16:54 UTC, jdach commented on src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
> +  const dropDownHeight = numOfItems => {
This styling can be made dynamic. 
From testing in browser, I believe you can just conditionally apply a height to the dropdownList class when there are more than 5 items and add padding to the bottom of dropdownContainer

2023-12-22 16:57 UTC, jdach requested changes
Not sure how this is related to just a height change, but the search bar is disappearing after clearing out the search. I am unable to reproduce this in qat or prod. 
https://github.com/fedspendingtransparency/fiscal-data/assets/77741207/f403cd4a-9410-468c-b34b-b6d58245c1b5

2023-12-27 15:26 UTC, wyattch commented
I was never able to replicate that search bar disappearing bug locally, so perhaps these dynamic changes will help?

2023-12-27 17:49 UTC, hmargy approved these changes
changes look good

2023-12-27 17:49 UTC, merged