Fdg 8391 deficit explainer api call updates
fedspendingtransparency/fiscal-data pull request #980
Opened 2024-01-03 23:37 UTC by chasls2

[FDG-8391](https://federal-spending-transparency.atlassian.net/browse/FDG-8391)

Test:

2024-01-09 16:01 UTC, jdach commented on src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
> +      {getFootNotesDateRange(previousFiscalYear, previousCalendarYear, currentRecordMonth)}, our national deficit has {deficitStatus} by $
This statement does not quite match the MAC in the case that the deficit remains unchanged. Instead of setting deficitDif to 'not changed', that should be the value of deficitStatus, and then we would not want to display any $ value after that

2024-01-09 16:21 UTC, jdach commented on src/layouts/explainer/heros/hero-helper.tsx
> +        <div style={{display: 'flex', justifyContent: 'center'}}>
Also, I am confirming what the width of this icon should be with Kylon. To me it looks a little large, but I will let them make that decision. I didn't see any design specs mentioned in the ticket

2024-01-09 16:23 UTC, jdach requested changes
Overall, changes are looking good. Other than the few notes I left on the code, could you add a test covering the 'not changed' case for the hero section?

2024-01-10 16:59 UTC, chasls2 commented
All fixes made

2024-01-11 16:19 UTC, jdach commented on src/layouts/explainer/heros/hero-helper.tsx
> +          <img src={doubleDash} alt="An open book with a coin above the pages." className={dashes} />
The alt text here does not match the icon

2024-01-11 16:24 UTC, chasls2 commented on src/layouts/explainer/heros/hero-helper.tsx
> +          <img src={doubleDash} alt="An open book with a coin above the pages." className={dashes} />
Weird.. I know I changed. that.. I must have reverted back..

2024-01-11 16:25 UTC, chasls2 commented on src/layouts/explainer/heros/hero-helper.tsx
> +          <img src={doubleDash} alt="An open book with a coin above the pages." className={dashes} />
fixed

2024-01-11 18:20 UTC, jdach approved these changes
Changes look good!

2024-01-11 18:21 UTC, merged